In [1]:
!pip install ydata-profiling

ERROR: Ignored the following versions that require a different python version: 4.0.0 Requires-Python >=3.7,<3.11; 4.1.0 Requires-Python >=3.7,<3.12; 4.1.1 Requires-Python >=3.7,<3.12; 4.1.2 Requires-Python >=3.7,<3.12; 4.10.0 Requires-Python >=3.7,<3.13; 4.11.0 Requires-Python >=3.7,<3.13; 4.12.0 Requires-Python >=3.7,<3.13; 4.12.1 Requires-Python >=3.7,<3.13; 4.12.2 Requires-Python >=3.7,<3.13; 4.13.0 Requires-Python >=3.7,<3.13; 4.14.0 Requires-Python >=3.7,<3.13; 4.15.0 Requires-Python >=3.7,<3.13; 4.15.1 Requires-Python >=3.7,<3.13; 4.16.0 Requires-Python >=3.7,<3.13; 4.16.1 Requires-Python >=3.7,<3.13; 4.17.0 Requires-Python >=3.7,<3.14; 4.18.0 Requires-Python >=3.10,<3.14; 4.18.1 Requires-Python >=3.10,<3.14; 4.18.2 Requires-Python >=3.10,<3.14; 4.18.3 Requires-Python >=3.10,<3.14; 4.2.0 Requires-Python >=3.7,<3.12; 4.3.0 Requires-Python >=3.7,<3.12; 4.3.1 Requires-Python >=3.7,<3.12; 4.3.2 Requires-Python >=3.7,<3.12; 4.4.0 Requires-Python >=3.7,<3.12; 4.5.0 Requires-Python >=3.7,<3.12; 4.5.1 Requires-Python >=3.7,<3.12; 4.6.0 Requires-Python >=3.7,<3.12; 4.6.1 Requires-Python >=3.7,<3.12; 4.6.2 Requires-Python >=3.7,<3.12; 4.6.3 Requires-Python >=3.7,<3.12; 4.6.4 Requires-Python >=3.7,<3.12; 4.6.5 Requires-Python >=3.7,<3.12; 4.7.0 Requires-Python >=3.7,<3.13; 4.8.3 Requires-Python >=3.7,<3.13; 4.9.0 Requires-Python >=3.7,<3.13
ERROR: Could not find a version that satisfies the requirement ydata-profiling (from versions: none)
ERROR: No matching distribution found for ydata-profiling

In [2]:
# importing  Libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from ydata_profiling import ProfileReport
import warnings
warnings.filterwarnings("ignore")

c:\Users\rites\AppData\Local\Programs\Python\Python313\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [5]:
# Loading Dataset
df = pd.read_csv("indian_roads_dataset.csv")
df.head(10)

,accident_id,city,state,latitude,longitude,date,time,hour,day_of_week,is_weekend,...,visibility,temperature,traffic_density,cause,accident_severity,vehicles_involved,casualties,is_peak_hour,festival,risk_score
0,0,Pune,Maharashtra,18.680827,73.930388,2023-10-22,5:00,5,Sunday,1,...,low,32,high,weather,fatal,2,2,0,NaN,0.85
1,1,Mumbai,Maharashtra,18.817732,72.790846,2023-05-21,4:00,4,Sunday,1,...,high,34,low,weather,major,4,3,0,NaN,0.10
2,2,Mumbai,Maharashtra,19.096889,72.819424,2024-07-10,13:00,13,Wednesday,0,...,low,21,medium,weather,minor,1,1,0,NaN,0.45
3,3,Chandigarh,Punjab,30.787805,76.847507,2025-03-30,11:00,11,Sunday,1,...,low,30,high,distraction,minor,5,2,0,NaN,0.65
4,4,Chennai,Tamil Nadu,12.965155,80.283313,2024-01-25,16:00,16,Thursday,0,...,high,24,low,distraction,minor,2,1,0,NaN,0.10
5,5,Delhi,Delhi,28.799490,77.049666,2024-07-29,8:00,8,Monday,0,...,high,36,high,overspeeding,fatal,4,4,1,NaN,0.65
6,6,Bangalore,Karnataka,13.064327,77.530941,2025-03-24,6:00,6,Monday,0,...,high,33,high,drunk driving,minor,4,4,0,NaN,0.30
7,7,Chandigarh,Punjab,30.786617,76.733947,2023-05-07,14:00,14,Sunday,1,...,high,25,low,weather,major,3,0,0,NaN,0.10
8,8,Hyderabad,Telangana,17.422447,78.464881,2022-02-25,3:00,3,Friday,0,...,low,22,low,poor road,minor,1,0,0,NaN,0.45
9,9,Bangalore,Karnataka,12.939033,77.498966,2024-03-31,4:00,4,Sunday,1,...,high,23,low,weather,minor,1,0,0,NaN,0.10

In [6]:
df.drop("time",axis =1)

,accident_id,city,state,latitude,longitude,date,hour,day_of_week,is_weekend,road_type,...,visibility,temperature,traffic_density,cause,accident_severity,vehicles_involved,casualties,is_peak_hour,festival,risk_score
0,0,Pune,Maharashtra,18.680827,73.930388,2023-10-22,5,Sunday,1,highway,...,low,32,high,weather,fatal,2,2,0,NaN,0.85
1,1,Mumbai,Maharashtra,18.817732,72.790846,2023-05-21,4,Sunday,1,urban,...,high,34,low,weather,major,4,3,0,NaN,0.10
2,2,Mumbai,Maharashtra,19.096889,72.819424,2024-07-10,13,Wednesday,0,urban,...,low,21,medium,weather,minor,1,1,0,NaN,0.45
3,3,Chandigarh,Punjab,30.787805,76.847507,2025-03-30,11,Sunday,1,urban,...,low,30,high,distraction,minor,5,2,0,NaN,0.65
4,4,Chennai,Tamil Nadu,12.965155,80.283313,2024-01-25,16,Thursday,0,highway,...,high,24,low,distraction,minor,2,1,0,NaN,0.10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,19995,Bangalore,Karnataka,13.092276,77.599571,2022-09-29,3,Thursday,0,urban,...,high,31,low,distraction,minor,3,2,0,NaN,0.10
19996,19996,Chennai,Tamil Nadu,13.172928,80.157062,2023-11-25,1,Saturday,1,urban,...,high,20,low,distraction,major,4,2,0,NaN,0.10
19997,19997,Chennai,Tamil Nadu,12.997170,80.150724,2022-06-18,15,Saturday,1,rural,...,high,22,low,weather,minor,3,3,0,NaN,0.10
19998,19998,Kolkata,West Bengal,22.454882,88.322213,2023-03-12,4,Sunday,1,highway,...,high,33,low,poor road,minor,1,0,0,NaN,0.10
19999,19999,Delhi,Delhi,28.510266,77.065301,2024-07-05,23,Friday,0,highway,...,low,39,high,overspeeding,minor,4,2,0,NaN,0.65

In [7]:
Profile = ProfileReport(df, title="Indian Roads Dataset EDA")
Profile.to_file("Indian_Roads_Dataset_EDA.html")

100%|██████████| 24/24 [00:00<00:00, 25.09it/s]1<00:00, 22.10it/s, Describe variable: risk_score]
Summarize dataset: 100%|██████████| 97/97 [00:08<00:00, 11.71it/s, Completed]
Generate report structure: 100%|██████████| 1/1 [00:03<00:00,  3.98s/it]
Render HTML: 100%|██████████| 1/1 [00:01<00:00,  1.28s/it]
Export report to file: 100%|██████████| 1/1 [00:00<00:00, 70.09it/s]